name: Build APK Barberia
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet supabase
          pip install --upgrade setuptools wheel

      - name: Build APK (Buscando main.py automáticamente)
        run: |
          # Buscamos dónde está el archivo main.py para no fallar por carpetas
          APP_PATH=$(find . -name "main.py" -print -quit | xargs dirname)
          echo "🚀 App encontrada en: $APP_PATH"
          # Ejecutamos el build desde esa carpeta con todos los permisos
          flet build apk --project "$APP_PATH" --verbose --no-interaction

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BarberApp-Final
          path: "**/build/apk/*.apk"
